### PR TITLE
Edited UserGuide and DeveloperGuide

### PR DESCRIPTION
**Pull request by aaronseahyh**
`UserGuide`: Added documentation for `MedicineInventory` commands.
`DeveloperGuide`: Added documentation for `MedicineInventory` implementation.

### CODE REVIEW

**Comment by jjlee050** [comment]
I only saw ur userguide. Comments as below:
- `add medicine` and etc commands. I don't think you want to have space in-between.
- `remove medicine`: To ensure consistency, use deletemedicine instead.

**Comment by jjlee050** [comment]
Developer guide comment:
- `3.2. MedicineInventory feature` change to `3.2.Medicine Inventory`

**Comment by aaronseahyh** [comment]
> I only saw ur userguide. Comments as below:
> 
> * [ ]  `add medicine` and etc commands. I don't think you want to have space in-between.
> * [ ]  `remove medicine`: To ensure consistency, use deletemedicine instead.
> * [ ]  `remove medicine`: Is it ideal for users to type the whole medicine name? You may wanna consider short form medicine name when addmedicine.
> * [ ]  `find medicine`: Same as the above comment.

Any reason to remove the space? Seems more user friendly and intuitive to include the space.

**Comment by jjlee050** [comment]
looks like we need to discuss abt the style of commands if not everyone will have a different style of command.

**Comment by aaronseahyh** [comment]
> Developer guide comment:
> 
> * [ ]  `3.2. MedicineInventory feature` change to `3.2.Medicine Inventory`
> * [ ]  Elaborate more on what does the `MedicineInventory` do.
> * [ ]  Under Step 1, remove instance of `AddressBook` to `ClinicIO`

I meant `AddressBook` intentionally, as the `MedicineInventory` will be initialized with the `AddressBook` that contains the `Patient` and `Doctor` details. Is the naming for the directory (for `Patient` and `Doctor`) correct?

**Comment by jjlee050** [comment]
by right, we need to remove all instances from the guides and from our codes too.

**Comment by jjlee050** [comment]
but currently, only guide doesn't have.

**Pull request merged**
