### PR TITLE
Edit UI look and feel

### PR DESCRIPTION
**Pull request by jjlee050**
- Make the panel look more like a card list instead of a normal list.
- Edit UI colors.
- Add "Opensans" font family for ClinicIO.

Signed-off-by: jjlee050 <josephlee050@gmail.com>

### CODE REVIEW

**Comment by jjlee050** [comment]
I call everyone to review becoz I am not good with colors and so far i only make changes with the list panel to look like card.

**Comment by jjlee050** [comment]
that is true but need ideas for the color. Using card is way better than a list.

**Comment by iamjackslayer** [comment]
How to pull this pr to my local machine?

**Comment by jjlee050** [comment]
Its not possible since its still merge pull request. The other way is to copy paste my file changed into ur machine.

**Comment by jjlee050** [comment]
I made some changes in terms of color and also the fonts to use.

**Comment by jjlee050** [comment]
I will take note of this. For now, I will just merge.

**Pull request merged**
