### PR TITLE
Add Queue Tab

### PR DESCRIPTION
**Pull request by iamjackslayer**
list, find and add command will auto switch the tab to persons tab
addappt command will auto switch the tab to appointment tab
enqueue, showqueue, dequeue command will autoswitch the tab to queue tab

### CODE REVIEW

**Comment by jjlee050** [comment]
U gt screenshot? And oso take note that i might change from person to patient (if hav time)

**Comment by jjlee050** [comment]
I believe you are working on changing person card and list panel to patient. can try to add some sample data? 1 or 2 is enough. Thx

**Comment by iamjackslayer** [comment]
@jjlee050 Oh I thought you're changing all persons to patient

**Comment by jjlee050** [comment]
k that means i need this pr and this #246 to be approved.

**Comment by iamjackslayer** [comment]
ok i am reviewing #246 now

**Comment by jjlee050** [comment]
hang on. i am still working on test case

**Comment by jjlee050** [comment]
can ask wad do u mean by autoswitch?

**Comment by iamjackslayer** [comment]
means for example currently the tab shown is persons tab, say if you enqueuepatient 3, then the tabpane will switch to queue tab (from persons tab)

**Comment by jjlee050** [comment]
u mean it work

**Comment by iamjackslayer** [comment]
yea

**Pull request merged**
