### PR TITLE
Refactor files

### LINKED ISSUE #128: Change all instances of AddressBook inside the code
**Describe the bug**
`AddressBook` instances are still in `ClinicIO`

**To Reproduce**
1. `Ctrl F` to find instances of `AddressBook`
2. Replace with `ClinicIO`

**Expected behavior**
Replace all instances of `AddressBook` to `ClinicIO`

### PR DESCRIPTION
**Pull request by jjlee050**
**Do not merge this. I need approve from all of u then can merge coz its major refractoring.**

I am calling everyone because I am doing major refaction to remove all addressbook instances in the project to ClinicIO. And so i will change the package naming if possible.

[Fix #128]

### CODE REVIEW

**Comment by jjlee050** [comment]
Change all instances of addressbook to clinicio in the src project

**Comment by jjlee050** [comment]
Do not merge this. I need approve from all of u then can merge coz its major refracting.

**Comment by iamjackslayer** [comment]
Just to clarify the term you used, you mean **refactoring** right? (as opposed to **refracting**)

**Comment by jjlee050** [comment]
Oops its refractoring

**Comment by iamjackslayer** [comment]
**refactor** bro. Just wanna make sure the terms are consistent across all commits/PRs so in future those changes can be found easily (ctrl + f, etc)

**Pull request merged**
