### PR TITLE
Edit color when hover over the card in PersonList.

### LINKED ISSUE #115: Edit color when hover over the card in PersonList.
List cards do not change color when hovered over. Only change when clicked.

### PR DESCRIPTION
**Pull request by jjlee050**
Fix #115
Help view and suggest.

Signed-off-by: jjlee050 <josephlee050@gmail.com>

### CODE REVIEW

**Comment by arsalanc-v2** [comment]
Might be too bright. I suggest #73C2FB

**Comment by jjlee050** [comment]
The color u suggest is for the hover text inside the card right?

**Comment by arsalanc-v2** [comment]
> The color u suggest is for the hover text inside the card right?

Yeah

**Comment by jjlee050** [comment]
Will try.

**Comment by jjlee050** [comment]
screenshot 2018-10-24 at 16 09 48

**Comment by arsalanc-v2** [comment]
Invert colours for background and font

**Comment by jjlee050** [comment]
screenshot 2018-10-25 at 16 53 41
This is inverted color. Is it ok?

**Comment by arsalanc-v2** [comment]
cardnonhover

Non hover

**Comment by arsalanc-v2** [comment]
cardhover

Hover

**Comment by arsalanc-v2** [comment]
I meant the above invert

**Comment by jjlee050** [comment]
k
hang on i try

**Comment by jjlee050** [comment]
screenshot 2018-10-25 at 17 54 32
The text color is weird.

**Comment by arsalanc-v2** [comment]
You're right it's probably best to keep to white background with black text for non hover

**Comment by jjlee050** [comment]
Anyone else got comment on the color? This is left hanging for 5+ days alr.

**Pull request merged**
