### PR TITLE
Implement ListAppt and CancelAppt

### PR DESCRIPTION
**Pull request by gingivitiss**
-add ui for appointments
-appointment list appears in a tab pane
-implemented listappt and cancelappt
-fixed storage for appointment

### CODE REVIEW

**Comment by jjlee050** [comment]
@gingivitiss 
screenshot 2018-11-02 at 14 52 34
Its empty?

**Comment by gingivitiss** [comment]
> @gingivitiss
> screenshot 2018-11-02 at 14 52 34
> Its empty. I try enter the list command and its still empty.

the line "browserPlaceholder.getChildren().add(analyticsDisplay.getRoot());" seems to be preventing the list from showing.

**Comment by gingivitiss** [comment]
right now im using the person stack pane. anyways i commented out the browser stack pane in the meantime

**Comment by jjlee050** [comment]
@arsalanc-v2 Can assist here on how u manage to put here appointment display and show the status bar footer at the same time?

**Comment by arsalanc-v2** [comment]
@gingivitiss do you need help?

**Comment by arsalanc-v2** [comment]
Use _browserPlaceholder_ to display appointments

You'll need to toggle the visibility of any other component being displayed using _browserPlaceholder_ (_analyticsDisplay_ and _browserPanel_)
You can do this by subscribing to events.
 
Example: when appointments need to be displayed, hide _analyticsDisplay_ and _browserPanel_ while making the appointments component visible.

**Comment by gingivitiss** [comment]
noted
i'll make a separate pr to do up that bit

**Pull request merged**
