### PR TITLE
Edit user guide

### PR DESCRIPTION
**Pull request by jjlee050**
- Edit formatting for command summary header.
- Reorganise features section

### CODE REVIEW

**Comment by arsalanc-v2** [comment]
I think you accidentally removed the updated data commands and inserted the old version

**Comment by jjlee050** [comment]
hang on. i check

**Comment by arsalanc-v2** [comment]
Nope it starts at line 422

**Comment by jjlee050** [comment]
=== Displaying patient statistics : `patientstats`
 Displays the following information about patients:
****
* A summary of the number of patients over various time periods.
* The number of patients segmented by each day of the week.
* The number of patients segmented by different time periods within a day.
****
 Format: `patientstats`
 === Displaying appointment statistics : `appointmentstats`
 Displays the following information about appointments:
****
* A summary of the number of scheduled appointments over various time periods.
* The availability of appointment slots as compared to the number of scheduled appointments.
* The proportion of appointments that are follow-ups, as opposed to walk-in.
****
Format: `appointmentstats`
 === Displaying doctor statistics : `doctorstats`
 Displays the following information about doctors:
****
* A summary of the average number of consultations per doctor over various time periods.
* The number of patient preferences for each doctor.
****
Format: `doctorstats`
 === Displaying medicine statistics : `medstats`
 Displays the following information about medicines:
****
* A summary of the quantity of medicines prescribed over various time periods.
* The average spending on medicines per patient.
* A breakdown of medicines by their quantity issued.
****
Format: `medstats`
 === Exporting patient records : `export`
 Exports patient data. +
Format: `exportpatient`

**Comment by jjlee050** [comment]
is it this?

**Comment by arsalanc-v2** [comment]
Yes this is correct.

**Pull request merged**
